// Team Name English Translation Dictionary for RapidAPI (FlashScore / SofaScore) Match Mapping
export const TEAM_TRANSLATIONS: Record<string, string> = {
  // Soccer Premier League
  "아스널": "Arsenal",
  "아스날": "Arsenal",
  "맨체스C": "Manchester City",
  "맨시티": "Manchester City",
  "맨체스U": "Manchester United",
  "맨유": "Manchester United",
  "리버풀": "Liverpool",
  "첼시": "Chelsea",
  "토트넘": "Tottenham Hotspur",
  "뉴캐슬U": "Newcastle United",
  "뉴캐슬": "Newcastle United",
  "브라이턴": "Brighton",
  "브라이튼": "Brighton",
  "애스턴빌": "Aston Villa",
  "아스톤빌라": "Aston Villa",
  "웨스트햄": "West Ham United",
  "크리스털": "Crystal Palace",
  "크리스탈": "Crystal Palace",
  "에버턴": "Everton",
  "에버튼": "Everton",
  "울버햄프": "Wolverhampton Wanderers",
  "울버햄튼": "Wolverhampton Wanderers",
  "풀럼": "Fulham",
  "본머스": "Bournemouth",
  "브렌트포": "Brentford",
  "브렌트포드": "Brentford",
  "노팅엄": "Nottingham Forest",
  "레스터": "Leicester City",
  "사우샘프": "Southampton",
  "입스위치": "Ipswich Town",

  // La Liga
  "레알마드": "Real Madrid",
  "레알마드리드": "Real Madrid",
  "바르셀로": "Barcelona",
  "바르셀로나": "Barcelona",
  "AT마드": "Atletico Madrid",
  "아틀레티코": "Atletico Madrid",
  "비야레알": "Villarreal",
  "소시에다": "Real Sociedad",
  "레알베티": "Real Betis",
  "세비야": "Sevilla",
  "발렌시아": "Valencia",
  "지로나": "Girona",
  "빌바오": "Athletic Bilbao",

  // Bundesliga
  "바이뮌헨": "Bayern Munich",
  "바이에른뮌헨": "Bayern Munich",
  "도르트문": "Borussia Dortmund",
  "도르트문트": "Borussia Dortmund",
  "레버쿠젠": "Bayer Leverkusen",
  "라이프치": "RB Leipzig",
  "슈투트가": "Stuttgart",
  "프랑크푸": "Eintracht Frankfurt",

  // Serie A
  "인테르": "Inter Milan",
  "인터밀란": "Inter Milan",
  "AC밀란": "AC Milan",
  "유벤투스": "Juventus",
  "아탈란타": "Atalanta",
  "로마": "AS Roma",
  "AS로마": "AS Roma",
  "나폴리": "Napoli",
  "라치오": "Lazio",
  "피오렌티": "Fiorentina",

  // Ligue 1
  "PSG": "Paris Saint-Germain",
  "파리생제르맹": "Paris Saint-Germain",
  "마르세유": "Marseille",
  "AS모나코": "Monaco",
  "모나코": "Monaco",
  "리옹": "Lyon",
  "릴": "Lille",

  // K League & Domestic
  "울산HDFC": "Ulsan HD",
  "울산": "Ulsan HD",
  "전북현대": "Jeonbuk Hyundai",
  "전북": "Jeonbuk Hyundai",
  "FC서울": "FC Seoul",
  "포항스틸": "Pohang Steelers",
  "포항": "Pohang Steelers",
  "광주FC": "Gwangju FC",
  "수원삼성": "Suwon Samsung Bluewings",
  "김천상무": "Gimcheon Sangmu",
  "제주SKFC": "Jeju United",
  "제주": "Jeju United",
  "대전하나": "Daejeon Hana Citizen",
  "강원FC": "Gangwon FC",
  "인천유나": "Incheon United",
  "대구FC": "Daegu FC",

  // MLB & KBO Baseball
  "샌프란시스코 자이언츠": "San Francisco Giants",
  "샌프란시스코자이언츠": "San Francisco Giants",
  "샌프란시스코": "San Francisco Giants",
  "샌프자이": "San Francisco Giants",
  "SF자이언츠": "San Francisco Giants",
  "LA다저스": "Los Angeles Dodgers",
  "LA 다저스": "Los Angeles Dodgers",
  "로스앤젤레스 다저스": "Los Angeles Dodgers",
  "뉴욕양키스": "New York Yankees",
  "뉴욕 양키스": "New York Yankees",
  "뉴욕양키": "New York Yankees",
  "보스턴 레드삭스": "Boston Red Sox",
  "보스턴레드삭스": "Boston Red Sox",
  "보스레드": "Boston Red Sox",
  "휴스턴 애스트로스": "Houston Astros",
  "휴스턴애스트로스": "Houston Astros",
  "휴스애스": "Houston Astros",
  "애틀랜타 브레이브스": "Atlanta Braves",
  "애틀랜타브레이브스": "Atlanta Braves",
  "애틀브레": "Atlanta Braves",
  "토론토 블루제이스": "Toronto Blue Jays",
  "토론토블루제이스": "Toronto Blue Jays",
  "토론블루": "Toronto Blue Jays",
  "뉴욕 메츠": "New York Mets",
  "뉴욕메츠": "New York Mets",
  "시카고 컵스": "Chicago Cubs",
  "시카고컵스": "Chicago Cubs",
  "시카컵스": "Chicago Cubs",
  "샌디에이고 파드리스": "San Diego Padres",
  "샌디에이고파드리스": "San Diego Padres",
  "샌디에이고": "San Diego Padres",
  "샌디파드": "San Diego Padres",
  "볼티모어 오리올스": "Baltimore Orioles",
  "볼티모어": "Baltimore Orioles",
  "볼티오리": "Baltimore Orioles",
  "클리블랜드 가디언스": "Cleveland Guardians",
  "클리블랜드": "Cleveland Guardians",
  "시애틀 매리너스": "Seattle Mariners",
  "시애틀": "Seattle Mariners",
  "미네소타 트윈스": "Minnesota Twins",
  "미네소타": "Minnesota Twins",
  "텍사스 레인저스": "Texas Rangers",
  "텍사스": "Texas Rangers",
  "필라델피아 필리스": "Philadelphia Phillies",
  "필라델피아": "Philadelphia Phillies",
  "밀워키 브루어스": "Milwaukee Brewers",
  "밀워키": "Milwaukee Brewers",
  "애리조나 다이아몬드백스": "Arizona Diamondbacks",
  "애리조나": "Arizona Diamondbacks",
  "세인트루이스 카디널스": "St. Louis Cardinals",
  "세인트루이스": "St. Louis Cardinals",
  "신시내티 레즈": "Cincinnati Reds",
  "신시내티": "Cincinnati Reds",
  "피츠버그 파이리츠": "Pittsburgh Pirates",
  "피츠버그": "Pittsburgh Pirates",
  "워싱턴 내셔널스": "Washington Nationals",
  "워싱턴": "Washington Nationals",
  "마이애미 말린스": "Miami Marlins",
  "마이애미": "Miami Marlins",
  "콜로라도 로키스": "Colorado Rockies",
  "콜로라도": "Colorado Rockies",
  "오클랜드 애슬레틱스": "Oakland Athletics",
  "오클랜드": "Oakland Athletics",
  "시카고 화이트삭스": "Chicago White Sox",
  "시카고화이트삭스": "Chicago White Sox",
  "탬파베이 레이스": "Tampa Bay Rays",
  "탬파베이": "Tampa Bay Rays",
  "캔자스시티 로열스": "Kansas City Royals",
  "캔자스시티": "Kansas City Royals",
  "LA 에인절스": "Los Angeles Angels",
  "LA에인절스": "Los Angeles Angels",
  "두산 베어스": "Doosan Bears",
  "두산베어스": "Doosan Bears",
  "두산": "Doosan Bears",
  "LG 트윈스": "LG Twins",
  "LG트윈스": "LG Twins",
  "LG": "LG Twins",
  "KIA 타이거즈": "KIA Tigers",
  "KIA타이거즈": "KIA Tigers",
  "기아": "KIA Tigers",
  "KIA": "KIA Tigers",
  "삼성 라이온즈": "Samsung Lions",
  "삼성라이온즈": "Samsung Lions",
  "삼성": "Samsung Lions",
  "키움 히어로즈": "Kiwoom Heroes",
  "키움히어로즈": "Kiwoom Heroes",
  "키움": "Kiwoom Heroes",
  "SSG 랜더스": "SSG Landers",
  "SSG랜더스": "SSG Landers",
  "SSG": "SSG Landers",
  "한화 이글스": "Hanwha Eagles",
  "한화이글스": "Hanwha Eagles",
  "한화": "Hanwha Eagles",
  "롯데 자이언츠": "Lotte Giants",
  "롯데자이언츠": "Lotte Giants",
  "롯데": "Lotte Giants",
  "KT 위즈": "KT Wiz",
  "KT위즈": "KT Wiz",
  "KT": "KT Wiz",
  "NC 다이노스": "NC Dinos",
  "NC다이노스": "NC Dinos",
  "NC": "NC Dinos",

  // NBA & KBL Basketball
  "레이커스": "Los Angeles Lakers",
  "골든워리": "Golden State Warriors",
  "골든스테이트": "Golden State Warriors",
  "셀틱스": "Boston Celtics",
  "불스": "Chicago Bulls",
  "닉스": "New York Knicks",
  "클리퍼스": "Los Angeles Clippers",
  "DB프로미": "Wonju DB Promy",
  "KCC이지스": "Busan KCC Egis",
  "SK나이츠": "Seoul SK Knights",
  "LG세이커스": "Changwon LG Sakers",
  "KT소닉붐": "Suwon KT Sonicboom"
};

export function translateTeamNameToEnglish(teamName: string): string {
  if (!teamName) return '';
  const trimmed = teamName.trim();
  if (TEAM_TRANSLATIONS[trimmed]) {
    return TEAM_TRANSLATIONS[trimmed];
  }

  // Partial match search
  for (const [key, val] of Object.entries(TEAM_TRANSLATIONS)) {
    if (trimmed.includes(key) || key.includes(trimmed)) {
      return val;
    }
  }

  return trimmed;
}
